# Generated by Django 5.2.10 on 2026-01-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewlog',
            unique_together=set(),
        ),
    ]
